### ISSUE TITLE
Waring:Now the archlinux source has changed his name....

### ISSUE THREAD

**Issue by name1e5s** [WuTianming/sfpkg-wtm#2]
Now you need this....

<code>[sfpkg]</code>
<code>SigLevel = Never</code>
<code>Server = http://name1e5s.coding.me/sfpkg/x86_64</code>

**Comment by WuTianming** [comment]
应该是warning吧（typo）

**Comment by WuTianming** [comment]
还有为什么是his

**Comment by WuTianming** [comment]
难道是百度翻译？233

**Comment by WuTianming** [comment]
是repo不是source

**Comment by WuTianming** [comment]
等我拿到电脑就改README.md
（学生真苦逼）

**Comment by name1e5s** [comment]
I think I was sleeping when I open this issue...

**Comment by WuTianming** [comment]
@name1e5s 是I think I was sleeping when I **opened** this issue

**Comment by WuTianming** [comment]
然而问题还没解决你就关issue干嘛

**Comment by WuTianming** [comment]
最近几次Arch源都连不上啊

**Comment by WuTianming** [comment]
@name1e5s Arch源连不上，是正在更新？

**Comment by WuTianming** [comment]
@name1e5s 有没有搞错，http://name1e5s.coding.me/是404

**Comment by name1e5s** [comment]
刚刚我还滚了一波。。。一会我看看

**Comment by name1e5s** [comment]
能用啊。。。对了，404是因为我这个直接拿coding.io的pages做的，没放index.html。。。源不行可能是你没有换源。。。之前的源让我删了

**Comment by WuTianming** [comment]
@name1e5s 
![screenshot from 2016-04-30 21-39-01](https://cloud.githubusercontent.com/assets/16624684/14936238/28ba6fe0-0f1c-11e6-9160-a37692cf83b5.png)
![screenshot from 2016-04-30 21-39-34](https://cloud.githubusercontent.com/assets/16624684/14936239/2953325c-0f1c-11e6-83fe-4e0beed679d9.png)

**Comment by name1e5s** [comment]
对啊。。。

**Comment by WuTianming** [comment]
@name1e5s 现在的源到底是什么？是我弄错了吗？

**Comment by name1e5s** [comment]
就是现在这个。。如果访问不了我明天早上看看。。。

**Comment by WuTianming** [comment]
@name1e5s 奇怪咯

**Comment by name1e5s** [comment]
在我的电脑上跑得好好的啊。。。
![Uploading 2016-05-01 09-12-12 的屏幕截图.png…]()

**Comment by name1e5s** [comment]
![](https://coding.net/u/name1e5s/p/pic/git/raw/master/2016-5-1.png)

**Comment by name1e5s** [comment]
https://coding.net/u/name1e5s/p/pic/git/raw/master/2016-5-1.png

**Comment by WuTianming** [comment]
呼... 能用了。
