### ISSUE TITLE
A problem with ArchLinux SFPKG Repo

### ISSUE THREAD

**Issue by WuTianming** [WuTianming/sfpkg-wtm#3]
@name1e5s 

Arch的SFPKG源内有三个包，sfpkg，sfpkg-wtm，sfpkg-wtm-git。

1. 应该添加软件包说明
2. 这三个包应该是互相冲突的，要标记一下Conflict

**Comment by name1e5s** [comment]
好的，但是鉴于我已经躺在了床上。。。明早再改

**Comment by WuTianming** [comment]
@name1e5s ~~我躺在床上刷笔记本...~~

问下，你那个coding.me的源是花钱在coding.net上买的？

**Comment by name1e5s** [comment]
不是。。。就是个pages。。。别人用来搭静态博客的那种pages

**Comment by name1e5s** [comment]
我正在考要不要在sourceforge上搭一个。。。这样我就有一堆镜像了。。。

**Comment by WuTianming** [comment]
@name1e5s 为什么不用GitHub Pages

**Comment by name1e5s** [comment]
Done

**Comment by name1e5s** [comment]
因为我的github pages 被我用来搭博客了
